### ISSUE TITLE
ply转splat转换报错了

### ISSUE THREAD

**Issue by chaoyang915506** [gotoeasy/gsbox#1]
![企业微信截图_17263078804930](https://github.com/user-attachments/assets/21474c15-151f-4020-ada6-e8c28d38bd04)
使用exe直接执行会报这个错误，是我用的姿势不对吗

**Comment by gotoeasy** [comment]
目前没有对输入做检查，使用时需要确保输入文件存在，输出的目录存在，ply也只是支持官方的3dgs格式

有空时再优化了

**Comment by gotoeasy** [comment]
window上命令输入要注意目录分隔符，通常一个`\`可以，但`\t` `\n` 之类出现的话就有问题了，你的姿势上分隔符出现了`\t`所以出错了

window上命令行正确的目录分隔符应该是 `\\`

**Comment by chaoyang915506** [comment]
OK 感谢

**Comment by gotoeasy** [comment]
v2.1.0版本已做了些改进

**Comment by chaoyang915506** [comment]
ok 感谢 非常好用
