### ISSUE TITLE
个别文件夹下转换报错

### ISSUE THREAD

**Issue by chaoyang915506** [gotoeasy/gsbox#3]
![image](https://github.com/user-attachments/assets/8feda7f6-9008-42de-9e07-254ca927beed)
![image](https://github.com/user-attachments/assets/6013ddc9-98f2-446d-8981-89f17259a296)
从最深文件夹到最浅层我试了一下没问题，只要叫rusatest文件夹下的文件程序就找不到了，如果换其他路径的深层偶发出错

![image](https://github.com/user-attachments/assets/547a131d-b1de-4466-99d4-84994c5ae115)
这样也行

**Comment by gotoeasy** [comment]
参考 #1

window下使用要注意分隔符问题，`\rusatest` 用`\\rusatest`，不然被识别为回车符了，类似还有 t 、n等等

**Comment by chaoyang915506** [comment]
![image](https://github.com/user-attachments/assets/7ce73921-4f48-4633-91f7-8ad2a1ec1f55)
D:\\learn_file\\exe\\gsbox.exe -i D:\\rusatest\\1117\\11172\\QuickPointcloud\\point_cloud\\iteration_7000\\point_cloud.ply -o D:\\rusatest\\1117\\11172\\QuickPointcloud\\point_cloud\\iteration_7000\\point_cloud.splat

**Comment by gotoeasy** [comment]
缺了命令参数吧 ply2splat

**Comment by chaoyang915506** [comment]
exe是最新的，出问题的是另外一台电脑，我按照那台电脑的文件夹层级创建后我的电脑就复现了这个问题，好像是卡在程序中的checkInputFileExists函数后，走不下去了，输出了usatest\1117\11172\QuickPointcloud\point_cloud\iteration_7000\point_cloud.ply

**Comment by gotoeasy** [comment]
确实，`v2.3.0` 已修复

**Comment by chaoyang915506** [comment]
OK 感谢
